# 工作流名称
name: E2E Tests with Cypress

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set npm registry to Taobao mirror
        run: npm config set registry https://registry.npmmirror.com/

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/routing.cy.js
          # 如果你的项目需要安装依赖，确保在 Cypress run 之前运行 npm install
          # install-command: npm ci # 或者 npm install